version: '3.8'

services:
  zodiac:
    build:
      context: .
      target: production
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-}
    image: zodiac:latest
    container_name: zodiac-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - zodiac-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  zodiac-network:
    driver: bridge
