import { SETTINGS_STORAGE_KEYS } from "./SettingsStorageKeys";
import type { TakeoutCategory } from "../types/Takeout";

export const TAKEOUT_FORMAT = "zozo-chat-takeout";
export const TAKEOUT_SCHEMA_VERSION = 1;

export const TAKEOUT_CATEGORIES: readonly TakeoutCategory[] = [
	"chats",
	"media",
	"personas",
	"settings",
	"themes",
	"loras",
	"pins",
	"roleplay",
	"apiKeys"
];

export const DEFAULT_TAKEOUT_CATEGORIES: readonly TakeoutCategory[] = TAKEOUT_CATEGORIES.filter(
	(category) => category !== "apiKeys"
);

export const TAKEOUT_SETTING_KEYS: Readonly<
	Record<Exclude<TakeoutCategory, "chats" | "media" | "personas">, readonly string[]>
> = {
	settings: [
		SETTINGS_STORAGE_KEYS.MAX_TOKENS,
		SETTINGS_STORAGE_KEYS.TEMPERATURE,
		SETTINGS_STORAGE_KEYS.MODEL,
		SETTINGS_STORAGE_KEYS.IMAGE_MODEL,
		SETTINGS_STORAGE_KEYS.IMAGE_EDIT_MODEL,
		SETTINGS_STORAGE_KEYS.AUTOSCROLL,
		SETTINGS_STORAGE_KEYS.STREAM_RESPONSES,
		SETTINGS_STORAGE_KEYS.ENABLE_THINKING,
		SETTINGS_STORAGE_KEYS.THINKING_BUDGET,
		SETTINGS_STORAGE_KEYS.RPG_GROUP_CHATS_PROGRESS_AUTOMATICALLY,
		SETTINGS_STORAGE_KEYS.ALLOW_PERSONA_PINGING,
		SETTINGS_STORAGE_KEYS.DYNAMIC_GROUP_CHAT_PING_ONLY,
		SETTINGS_STORAGE_KEYS.FULL_WIDTH_CHAT,
		SETTINGS_STORAGE_KEYS.UI_SCALE,
		SETTINGS_STORAGE_KEYS.PREFER_PREMIUM_ENDPOINT,
		SETTINGS_STORAGE_KEYS.PREFER_PREMIUM_IMAGE_ENDPOINT
	],
	themes: [SETTINGS_STORAGE_KEYS.THEME_SETTINGS],
	loras: [SETTINGS_STORAGE_KEYS.LORAS],
	pins: [
		SETTINGS_STORAGE_KEYS.PINNED_CHAT_IDS,
		SETTINGS_STORAGE_KEYS.PINNED_PERSONA_IDS,
		SETTINGS_STORAGE_KEYS.PINNED_MODEL_IDS
	],
	roleplay: [
		SETTINGS_STORAGE_KEYS.DELIMITER_PRESET,
		SETTINGS_STORAGE_KEYS.CUSTOM_DIALOGUE_INSTRUCTION,
		SETTINGS_STORAGE_KEYS.CUSTOM_ACTION_INSTRUCTION,
		SETTINGS_STORAGE_KEYS.CUSTOM_THOUGHT_INSTRUCTION,
		SETTINGS_STORAGE_KEYS.ROLEPLAY_SUGGESTION_MODEL,
		SETTINGS_STORAGE_KEYS.ROLEPLAY_FAVORITE_ACTIONS,
		SETTINGS_STORAGE_KEYS.ROLEPLAY_CUSTOM_CATEGORIES,
		SETTINGS_STORAGE_KEYS.ROLEPLAY_CUSTOM_ACTIONS
	],
	apiKeys: [SETTINGS_STORAGE_KEYS.API_KEY, SETTINGS_STORAGE_KEYS.OPENROUTER_API_KEY]
};
