name: Release Drafter

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: read

jobs:
    update-release-draft:
        runs-on: ubuntu-latest

        steps:
            - name: Update draft release
              uses: release-drafter/release-drafter@v7
              with:
                  config-name: release-drafter.yml
